"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()  # Load environment variables from .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&n^6x(s+mc4cd4no$7qh%ao!wk4gc@t1@n6+@4a%u73$zy2p30'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory_app',
]

# ─────────────────────────────────────────────────────────────────────────────
# JAZZMIN — White-label & Branding
# ─────────────────────────────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    # ── Browser tab / page title ──────────────────────────────────────────────
    "site_title": "Pest Control OS",

    # ── Top-left header text (shown when no logo is set) ─────────────────────
    "site_header": "Pest Control OS",

    # ── Collapsed-sidebar brand text ──────────────────────────────────────────
    "site_brand": "PC OS",

    # ── Logo (place file at:  inventory_app/static/inventory_app/img/logo.png)
    # "site_logo": "inventory_app/img/logo.png",
    # "login_logo": "inventory_app/img/logo.png",

    # ── Logo dimensions (px) — tune to your actual image ─────────────────────
    # "site_logo_classes": "img-circle",
    # "login_logo_classes": "img-fluid",

    # ── Welcome text on the login card ───────────────────────────────────────
    "welcome_sign": "Welcome to the Operations Portal",

    # ── Footer copyright ──────────────────────────────────────────────────────
    "copyright": "Pest Control OS © 2026. All rights reserved.",

    # ── Global search models ──────────────────────────────────────────────────
    "search_model": ["auth.User", "inventory_app.Job"],

    # ── Top navigation links
    #    Empty list = hides "View Site" and any other default top links.
    "topmenu_links": [
        # Internal admin links only — no "View Site" back to the worker app.
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    # ── User menu (top-right avatar dropdown) ─────────────────────────────────
    "usermenu_links": [
        {"name": "Change Password", "url": "admin:password_change", "icon": "fas fa-key"},
    ],

    # ── Sidebar: show all apps that are in INSTALLED_APPS ────────────────────
    "show_sidebar": True,
    "navigation_expanded": True,

    # ── Hide the "View Site" button in the sidebar header ────────────────────
    "hide_apps": [],
    "hide_models": [],

    # ── Per-model & per-app icons (FontAwesome 5 Free) ───────────────────────
    "icons": {
        # Built-in auth app
        "auth":                              "fas fa-shield-alt",
        "auth.user":                         "fas fa-user-tie",
        "auth.Group":                        "fas fa-users",

        # Our app
        "inventory_app":                     "fas fa-industry",
        "inventory_app.Job":                 "fas fa-briefcase",
        "inventory_app.InventoryItem":       "fas fa-flask",
        "inventory_app.InventoryUsageLog":   "fas fa-clipboard-list",
    },

    # ── Fallback icon for any model not listed above ──────────────────────────
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",

    # ── Disable the live UI customiser (production-safe) ─────────────────────
    "show_ui_builder": False,

    # ── Misc UX ──────────────────────────────────────────────────────────────
    "related_modal_active": True,       # Opens FK lookups in a modal, not a new tab
    "changeform_format": "horizontal_tabs",  # Fieldsets as tabs on the change form
}

# ─────────────────────────────────────────────────────────────────────────────
# JAZZMIN — Theme & UI Tweaks
# ─────────────────────────────────────────────────────────────────────────────
JAZZMIN_UI_TWEAKS = {
    # ── Bootswatch theme ──────────────────────────────────────────────────────
    # "litera" = clean, readable, professional — ideal for B2B SaaS dashboards.
    # Other great options: "cosmo", "flatly", "pulse", "united"
    "theme": "litera",

    # ── Navbar (top bar) ──────────────────────────────────────────────────────
    # "navbar-white navbar-light" = crisp white bar, dark text, no chrome.
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,               # Sticky top navbar

    # ── Sidebar ───────────────────────────────────────────────────────────────
    # "sidebar-light-primary" = white/light-gray sidebar, primary-colour accents.
    # Remove "dark" feel entirely.
    "sidebar": "sidebar-light-primary",
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_nav_compact_style": True,  # Tighter line-height — more items visible
    "sidebar_nav_child_indent": True,
    "sidebar_nav_flat_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_disable_expand": False,

    # ── Body / typography ─────────────────────────────────────────────────────
    "body_small_text": False,
    "navbar_small_text": False,
    "footer_small_text": True,          # Footer in a slightly smaller font

    # ── Brand block (top-left of sidebar) ────────────────────────────────────
    "brand_colour": "navbar-primary",   # Accent colour strip behind the brand
    "brand_small_text": False,

    # ── Accent colour (active items, badges, highlights) ─────────────────────
    "accent": "accent-primary",

    # ── Layout ───────────────────────────────────────────────────────────────
    "layout_boxed": False,              # Full-width layout
    "footer_fixed": False,

    # ── Button styles ─────────────────────────────────────────────────────────
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-outline-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },

    # ── Sticky action buttons on change forms ─────────────────────────────────
    "actions_sticky_top": True,         # "Save"/"Delete" buttons stay visible on scroll
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Automatically detects PostgreSQL from DATABASE_URL environment variable
# Falls back to local SQLite if not present (perfect for development)

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Production: Use PostgreSQL from Neon.tech or Supabase
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Development: Use local SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth redirects
LOGIN_REDIRECT_URL = 'job_list'
LOGOUT_REDIRECT_URL = 'login_choice'
LOGIN_URL = 'login_choice'
