# Generated by Django 6.0.4 on 2026-04-19 14:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='inventoryusagelog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory Usage Log', 'verbose_name_plural': 'Inventory Usage Logs'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-execution_date', '-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='worker',
        ),
        migrations.AddField(
            model_name='inventoryusagelog',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin-only notes for this log entry (e.g. reason for retroactive entry).', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(default=1, help_text='Field worker assigned to this job.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='execution_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='The actual date the job was executed. Admins can backdate this for retroactive data entry.'),
        ),
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes or special instructions for this job.', null=True),
        ),
        migrations.AlterField(
            model_name='inventoryusagelog',
            name='amount_returned',
            field=models.PositiveIntegerField(default=0, help_text='Units brought back to the warehouse.'),
        ),
        migrations.AlterField(
            model_name='inventoryusagelog',
            name='amount_taken',
            field=models.PositiveIntegerField(default=0, help_text='Units checked out from the warehouse.'),
        ),
        migrations.AlterField(
            model_name='inventoryusagelog',
            name='amount_used',
            field=models.PositiveIntegerField(default=0, help_text='Units actually consumed on-site.'),
        ),
        migrations.AlterField(
            model_name='inventoryusagelog',
            name='photo_proof',
            field=models.ImageField(blank=True, help_text='Photo showing remaining / returned bottles.', null=True, upload_to='return_proofs/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='container_number',
            field=models.CharField(help_text='Identifier for the shipping container.', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduled_date',
            field=models.DateField(help_text='The date the job is/was scheduled.'),
        ),
    ]
