# Generated by Django 6.0.2 on 2026-04-21 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Location name, e.g. 'Mundra', 'Ahmedabad'.", max_length=100, unique=True)),
                ('address', models.CharField(blank=True, help_text='Full street address or landmark.', max_length=300)),
            ],
            options={
                'verbose_name': 'Warehouse Location',
                'verbose_name_plural': 'Warehouse Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Units currently stored at this location.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory_app.inventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory_app.warehouselocation')),
            ],
            options={
                'verbose_name': 'Stock Level',
                'verbose_name_plural': 'Stock Levels',
                'ordering': ['item__name', 'location__name'],
                'unique_together': {('item', 'location')},
            },
        ),
    ]
