# Generated by Django 6.0.2 on 2026-04-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_add_warehouse_location_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image of the chemical/item.', null=True, upload_to='inventory_images/'),
        ),
    ]
