# Generated by Django 6.0.2 on 2026-04-22 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_inventoryitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'CHA',
                'verbose_name_plural': 'CHAs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Exporter',
                'verbose_name_plural': 'Exporters',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='cargo_description',
            field=models.TextField(blank=True, help_text='Description of the cargo.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='certificate_name',
            field=models.CharField(blank=True, help_text='Name to appear on certificates.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_third_party_vendor',
            field=models.BooleanField(default=False, help_text='Indicates if a third-party vendor is executing the job.'),
        ),
        migrations.AddField(
            model_name='job',
            name='quantity_pkgs',
            field=models.CharField(blank=True, help_text="Quantity and packaging type (e.g., '100 Bags').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='site_location',
            field=models.CharField(blank=True, help_text='Specific site location for the job.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject line for reports/certificates.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='working_address',
            field=models.TextField(blank=True, help_text='Full working address.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cha',
            field=models.ForeignKey(blank=True, help_text='Customs House Agent handling this job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='inventory_app.cha'),
        ),
        migrations.AddField(
            model_name='job',
            name='exporter',
            field=models.ForeignKey(blank=True, help_text='Exporter for this shipment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='inventory_app.exporter'),
        ),
    ]
