# Generated by Django 6.0.2 on 2026-04-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_cha_exporter_job_cargo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch name.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_id_bill_to',
            field=models.CharField(blank=True, help_text='Customer ID (Bill To).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='remarks',
            field=models.TextField(blank=True, help_text='Optional remarks.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='task_description',
            field=models.TextField(blank=True, help_text='Task description.', null=True),
        ),
    ]
