# Generated by Django 6.0.2 on 2026-04-22 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_job_branch_job_customer_id_bill_to_job_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='other_supporting_work',
            field=models.TextField(blank=True, help_text='Other supporting work details.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stock_warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse location for stock deduction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='inventory_app.warehouselocation'),
        ),
    ]
