# Generated by Django 6.0.2 on 2026-04-22 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0007_job_other_supporting_work_job_stock_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cha',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cha',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exporter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exporter',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='dosage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry Date', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='fumigation_date',
            field=models.DateField(blank=True, help_text='Date of Fumigation', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Date of Issue', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='method_application',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='port_of_loading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stack_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vessel_voyage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Consignee / Client for this shipment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='inventory_app.client'),
        ),
    ]
