# Generated by Django 6.0.2 on 2026-04-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0008_client_cha_city_cha_country_exporter_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='total_stock',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_of_measurement',
            field=models.CharField(choices=[('Liters', 'Liters'), ('Milliliters', 'Milliliters'), ('Kilograms', 'Kilograms'), ('Grams', 'Grams'), ('Units', 'Units'), ('Pieces', 'Pieces')], default='Units', help_text='Unit of measurement for this item.', max_length=50),
        ),
    ]
