# Generated by Django 6.0.4 on 2026-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0009_remove_inventoryitem_total_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryusagelog',
            name='amount_returned',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Units brought back to the warehouse (supports decimals).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryusagelog',
            name='amount_taken',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Units checked out from the warehouse (supports decimals, e.g. 0.4 L).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryusagelog',
            name='amount_used',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Units actually consumed on-site (supports decimals).', max_digits=10),
        ),
    ]
