# Generated by Django 6.0.4 on 2026-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0010_decimal_amount_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='commodity_country_of_origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='consignment_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='datetime_commenced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='datetime_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='destination_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='enclosure_type',
            field=models.CharField(blank=True, choices=[('Sheeted Enclosure', 'Sheeted Enclosure'), ('Fumigation Chamber', 'Fumigation Chamber'), ('Un-sheeted Container', 'Un-sheeted Container'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='final_tlv_reading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='gross_weight',
            field=models.CharField(blank=True, help_text="Include 'KGS'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='net_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='target_of_fumigation',
            field=models.CharField(blank=True, choices=[('Commodity', 'Commodity'), ('Container', 'Container'), ('Packing', 'Packing'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
