# Generated by Django 6.0.2 on 2026-04-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0012_job_additional_declaration_job_applied_dose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accreditation_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='treatment_provider_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
