# Generated by Django 6.0.2 on 2026-05-06 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0013_job_accreditation_number_job_treatment_provider_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_workers',
            field=models.ManyToManyField(help_text='Workers assigned to this job.', related_name='assigned_jobs_multi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='chemical_amount',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Amount of chemical to take.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='chemical_item',
            field=models.ForeignKey(blank=True, help_text='Chemical to be used for this job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='inventory_app.inventoryitem'),
        ),
        migrations.AddField(
            model_name='job',
            name='chemical_unit',
            field=models.CharField(blank=True, choices=[('Liters', 'Liters'), ('Milliliters', 'Milliliters'), ('Kilograms', 'Kilograms'), ('Grams', 'Grams'), ('Units', 'Units'), ('Pieces', 'Pieces')], help_text='Unit for the chemical amount.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='execution_address',
            field=models.TextField(blank=True, help_text='Address where the job will be executed.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse to take the chemical from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs_source', to='inventory_app.warehouselocation'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='New Job', help_text='e.g., Mundra Fumigation', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='[Deprecated] Field worker assigned to this job.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
