# Generated by Django 6.0.4 on 2026-05-08 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0014_job_assigned_workers_job_chemical_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Proof-of-work photo uploaded by the field worker.', upload_to='job_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(help_text='The job this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory_app.job')),
            ],
            options={
                'verbose_name': 'Job Image',
                'verbose_name_plural': 'Job Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
